### ISSUE TITLE
[mid-bootcamp-project] Claudia Carloni

### ISSUE THREAD

**Issue by ClauCarloni** [Ironhack-Data-0621-Remote/mid-bootcamp-project#1]
https://github.com/ClauCarloni/Mid-Bootcamp-Project

**Comment by AnaAGG** [comment]
# mid bootcamp project 

Hello hello Claudia 🙋🏻‍♀️ , here we go with the revision of your project 

## README

Wow Claudia, you have a very completed readme 😉!! But... there is always something we can tell you. Here's a list of some of the details I've seen or that are missing: 

- What happened at the end of your readme? You have a `conclusion section` but without any conclusion

- Create a new section on your reame with the libraries information that you used. And... if you include the links to the official documentationm they will be perfect!


- Suuuper 🔝 that you include a little description of the columns and the info given by each of the columns.

- While you have a description of the columns, I was missing a more in-depth description of the dataset. What information does it give us, what are we going to do with it in a more detailed way etc. 

Otherwise everything perfect Claudia, good job 💪! 

## Repository structure

Regarding the structure of the repo, in general it is very good Claudia. As a detail:
- Your jupyter is very organised and very clear, congratulations 👏🏽

- You can create different folders, such as for example

    - Notebooks, where you store the jupyters you have worked on.
    - data: where you store the csv you work with throughout the project
    - SQL: where you store sql files

## Code Syntax

- In python it is a good practice to hace the functions in a `.py` support file where we have all the functions we will use in jupyter.

    🔴 If you have any question on how to do this, let me know and we'll chech it out.
- Regarding the functions, when we write a function it mandatory to create a docstring. 

    *What is it?*

    Is a string that give us the functionality of the code. What to put in the docstring of a function?

    - What the function does
    - The parameters it receives and what type they are
    - What it returns

        ```python
        # taking one of your functions as an example:

        def clean_header(df):
            '''
            Clean the columns names
            Args:
                df (dataframe): target dataframe to be cleaned
            Returns: 
                A dataframe with the columns' name cleaned
            '''
                pattern = '[\W]'
                df.columns = [x.lower().replace(" ", "_") for x in df.columns]
                df.columns = [re.sub(pattern, "", x) for x in df.columns]
                return df
        ```
    [Here](https://www.datacamp.com/community/tutorials/docstrings-python) some documentation about docstrings in python

- In the exploration part where you make the crosstables for centain columns, it would have been nice if you had added comments explaining what the tables show us. WE are data analysts, it is not enough for us just to put the lines of code that give us tge results, we must know how to interpret them 😉! 
-Although your jupyter is very organised and clear, I think it need a bit more documentation, i.e. better documentation what you are doing at each step, so that the reader doesn´t get lost in the workflow. 

- Regarding the KNN model, when you choose the best value of k you did it perfect. As a detail, in pyhton we have the `KElbowVisualizer` method which allow us to select optimal number of cluster in a simple way by fitting the model with a range of values. 

    [Here](https://www.scikit-yb.org/en/latest/api/cluster/elbow.html) some documentation. 

    ```python
    # here an example of what the code would look like

    # set the model
    model = KMeans()

    #inizialice the Visuaized. k correspond with the range of k we want to test 
    visualizer = KElbowVisualizer(model, k=(2,15), metric='silhouette')

    # fit the model for all the k created in the previous step
    visualizer.fit(X)  

    # return a plot highlighting the optimum number of k     
    visualizer.show()
    ```
## TODOs
Overll very good work on the project Claudia. I leave here a summary of the most importatn things I have commented in the review:
- Try to finish the read to make it perfect 
- Functions to `.py` file
- Document the jupyter a bit more
- Document the functions
- Add the libraries to the readme and don't leave it unfinished


Come on Claudia!! Good job, keep un the good work 💪🔥

![image](https://user-images.githubusercontent.com/75084991/132395251-a0e5dc39-573e-4c1d-b0ab-b45a0d1109c0.png)
