### ISSUE TITLE
Mid Term Project Regression_ Antonia Bloch [missing Tableau]

### ISSUE THREAD

**Issue by AntoniaBl** [Ironhack-Data-0621-Remote/mid-bootcamp-project#11]
Mid Term Project Regression_ Antonia Bloch  - missing Tableau still - will upload this during the day :)

https://github.com/AntoniaBl/Mid-Project.git

**Comment by fromeropablo** [comment]
# Mid-Bootcamp-Project

Hello Antonia! Let's gonna check your mid-bootcamp project!!

### 1. ReadME and Repo Structure

First of all, good READMe! You have explained how your project is developing and what steps are you taking every time, that's really cool! The structured it's good but you can always your presentation with some tricks.

Just a few details:

- Good work showing the Python modules that you used for your project but you can do it in a prettier way:
```markdown
[Pandas](https://pandas.pydata.org/docs/)
```

- It's important to create a good storytelling. Your projects won't be just your code, idea and data, but also the way that you present it to the world! For example, you can add some images as I'm gonna show you:
```markdown
![Zones of the court](./images/polygon_court.png)
```
The first part of the line, the one inside square brackets, represents the words that should appear in case that the image doesn't show properly. The second part is the image itself. To do in the same way you should create a folder in your repo (from Visual Studio) called `images` and save the images you wanna show there.  

- It would be great if you add a little explanation about the meaning of the columns of your dataset. It helps to orientate readers on what they are gonna see in your project. 

- About the structure of your repo is not very clear. It's better to create folders in Visual Studio Code to store your deliverable files, function files and images files. You will help readers to understand your work better and find easily every file. 

### 2. SQL

Okay, so now it's time to check your SQL exercise. The set of questions is very complete and it was added to reinforce your knowledge of such an important skill as it is manage structured databases. 

Great work in this part, you have answered in such a great way, congrats!

### 3. Cleaning, processing and modeling your data

During this part you had to deal with cleaning and preprocessing techniques that you have been learning during the course many times. 

It would be great if in the future you are able to import your database in a jupyter notebook directly from SQL. 

Also, remember that every cleaning task that you complete can be recycled in a function to save code lines and add clarity to your coding work. Good work using key plots for checking outliers, distributions and correlations. 

Be careful about the treatment of categorical variables. It's better to assign different weights to them in order to maintain the number of variables of your dataset. Having more than hundred variables will add too much noise to your dataset when you have to create models from it. 

In variables like `bedrooms` and similar I will not change anything by HotEncoder or creating dummies because of I told you above. The variable itself is explained by default in these cases. 

Good work in the final part creating good models with a high R2, but as I said tke into account that the less variable giving you the higher R2, the better. 

Good work at all, but I know that you can do a better job. You have shown it previously so, keep working and your final project will be awesome for sure!
