### ISSUE TITLE
[P2-midbootcamp-project-Classification-Rita]

### ISSUE THREAD

**Issue by ritasilv** [Ironhack-Data-0621-Remote/mid-bootcamp-project#15]
https://github.com/ritasilv/P2-Credit-Card-Revival.git

**Comment by fromeropablo** [comment]
# Mid-Bootcamp-Project

Hello Rita! Let's gonna check your mid-bootcamp project!!

### 1. ReadME and Repo Structure

First of all, great  pic in your ReadME! That's what we are looking for in a repo presentation!! Also you have explained how your project is developing and what steps are you taking every time, that's really cool! The structured it's great and adding images give readers a better vision and, obviously, more interest on what you are doing.

Just a few details:

- Good work showing the Python modules that you used for your project but you can do it in a prettier way:
```markdown
[Pandas](https://pandas.pydata.org/docs/)
```

- It would be great if you add a little explanation about the meaning of the columns that you have in your dataset. It helps to orientate readers on what they are gonna see in your project. 

- Also, it would be really cool if you save some key plots from your jupyter notebook as images and upload it in your ReadME. It will be valuable in your presentation.

- Great work in the structure of your repo. It's very clear but remember to keep Tableau files in the folder that you created


Anyway, really good job in this part!

### 2. SQL

Okay, so now it's time to check your SQL exercise. The set of questions is very complete and it was added to reinforce your knowledge of such an important skill as it is manage structured databases. 

Great work in this part, you have answered in such a great way, congrats!

- In question **8** you did a great job using `RANK` but you can do it in an easier way:
```sql
select Customer_Number from credit_card_data
order by Average_Balance desc
limit 10;
```

- Something similar happens in question **14**. In this case, the easier way would be like this:
```sql
select Offer_Accepted, count(Offer_Accepted)
from credit_card_data
group by Offer_Accepted;
```

- Again, your query is really good in question **17**, using complex clauses, that's great honestly, but it's always better to simplify our queries. It would be like this:
```sql
select * from credit_card_data 
order by Q1_balance asc 
limit 10,1;
```

### 3. Cleaning, processing and modeling your data

During this part you had to deal with cleaning and preprocessing techniques that you have been learning during the course many times. 

It would be great if in the future you are able to import your database in a jupyter notebook directly from SQL. 

Also, remember that every cleaning task that you complete can be recycled in a function to save code lines and add clarity to your coding work. Good work using key plots for checking outliers, distributions and correlations. 

Perfect job explaining what you are doing in every moment and giving some final considerations, congrats for it because it's really important! 

It seems that you have mastered all the preprocessing data tasks and it's really really good. Moreover, you have tried a lot of models in the Machine Learning part understanding the results and giving a conclusion for each of them.

Great job overall in this project, specially in the Python part, congrats!! Keep working in the same way and your final project will be great for sure!
