### ISSUE TITLE
 mid-bootcamp-project [ignacio]

### ISSUE THREAD

**Issue by ignaciolorenzo** [Ironhack-Data-0621-Remote/mid-bootcamp-project#18]
https://github.com/ignaciolorenzo/mid-project-classification

**Comment by AnaAGG** [comment]
# mid bootcamp project

Hello hello Ignacio 🙋🏻‍♀️ , here we go with the revision of your project 

## README

Overall your readme is perfect, only a couple of tips for the future: 

- If you include the links to the official documentationm they will be perfect!

- Maybe you could have commented a bit more on what the csv is about, what data we have, what information it gives us and maybe a little description of the variables for those people who are not familiar with this kind of data. You have two readme but its better that you have only one. 

## Repo structure

Let's go with the structure. To get a more structured repo you can: 

- Create a `data` folder where you store the `csv`
  
- Create a `Notebook` folder where you store the jupyters notebooks. In addition, if you have more than one jupyter you can also numerate the jupyters to know the workflow order. 
  
- Create the `src` folder with the `.py` file with the functions used in the jupyter. 

- Create a `sql` folder with the SQL scripts. 

## Code syntax

- Remember the functions to the `.py` file. 

- Let`s go with the docstrings. 

    You have the docstrings in your functions, but as always in python we have some convenctions about this:

    What should a docstring have?

    - What the function does
    - The parameters it receives and what type they are
    - What it returns

        ```python
        # taking one of your functions as an example:

        def clean_headers(df):
            '''
            Clean the columns names
            Args:
                df (dataframe): target dataframe to be cleaned
            Returns: 
                A dataframe with the columns' name cleaned
            '''
            cols = []
            for c in df.columns:
                c = c.lower().replace(" ", "_").replace("#", "n")
                cols.append(c)
            df.columns = cols
        ```
    [Here](https://www.datacamp.com/community/tutorials/docstrings-python) some documentation about docstrings in python

- In this part *3.1.1. Some numerical columns should be categoricals due to the reduced amount of value types they contain:*

    You repeated the same code 4 times, but imagine that you have 20 columns... maybe it will be imposible! 

    So... the best option is create a for loop

    ```python
    # create a list with the target columns 

    target_columns = ['n_bank_accounts_open', 'n_credit_cards_held','n_homes_owned', 'household_size']

    # then iterate for the list to change their type

    for i in target_columns:
        df.[i].astype('object')
    ```
    
- Good work with the functions, small with specific objectives. This is how you define a good function!

- Super well calling functions inside other functions. And by creating different functions for different models, get the results... 


## TODOs

As a recap of the review:

- Some details in the readme like libraries links, workflow structure
- The `.py` file
- Docstring in the functions
- More structured repo

Overall you have a great job 💪, but as a highlight of the TODOs I miss more development of the conclusions. What is the best model, what do the correlations you draw mean, which customers are going to receive offers and which are not?

![image](https://user-images.githubusercontent.com/75084991/133882244-74e51ec9-e94a-4d5a-978c-8ff4e1b0bec9.png)
