### ISSUE TITLE
[mid-bootcapm-project] Karolin Diede

### ISSUE THREAD

**Issue by KaroD123** [Ironhack-Data-0621-Remote/mid-bootcamp-project#3]
https://github.com/KaroD123/Project-2-mid-bootcamp-

**Comment by fromeropablo** [comment]
# Mid-Bootcamp-Project

Hello Karo! Let's gonna check your mid-bootcamp project!!

### 1. ReadME

First of all, you have a great ReadME, that's what we are looking for when we repeat everytime that you have to do a good ReadME. Very well structured, clean and with every section of your project explained, congrats!

Just a few details:

- Good work showing the Python modules that you used for your project but you can do it in a prettier way:
```markdown
[Pandas](https://pandas.pydata.org/docs/)
```
Similar to what I told you before, the first part is the title or what every user will see in your repo and the second part is the link to the documentation of that module. It will appear in Github in blue words as a hyperlink. 

- Great that you added a little explanation about the meaning of the columns of your dataset. It helps to orientate readers on what they are gonna see in your project. 

Amazing that you have solved almost every issue that you had in the previous project, that's improvement!

At all, really good job in this part!

### 2. SQL

Okay, so now it's time to check your SQL exercise. The set of questions is very complete and it was added to reinforce your knowledge of such an important skill as it is manage structured databases. 

Great work in this part, you have answered in such a great way, congrats!

- At the beginning, it's preferred to create the database and drop any possible existing table or database. It would be like this:
```sql
drop table if exists creditcardmarketing;
create table credit_card_data  (
	Customer_Number	int,
    Offer_Accepted varchar(20),
	Reward varchar(20),  
	Mailer_Type varchar(20),
    Income_Level varchar(20),
    Bank_Accounts_Open int,
    Overdraft_Protection varchar(20) ,
    Credit_Rating varchar(20),
    Credit_Cards_Held int,
    Homes_Owned int,
    Household_Size int,
    Own_Your_Home varchar(20),
    Average_Balance float,
    Q1_Balance float,
    Q2_Balance float,
    Q3_Balance float,
    Q4_Balance float,
    primary key (Customer_Number)
    );
```

- In exercise **5** you had to drop the column *Q4_balance* and then select your database in order to check if you dropped the column successfully.
```sql 
ALTER TABLE creditcardmarketing
DROP column Q4_Balance;

SELECT * FROM creditcardmarketing
LIMIT 10;
```

- In exercise **15** your query seems good for what we asked, but it exists at least one option saving some code lines. It would be like this:
```sql
select credit_rating, round(avg(Average_balance),2)
from creditcardmarketing
where credit_rating in ('High','medium')
group by credit_rating; 
```
- Finally, in last question (**17**), you can reduce your code lines aswell. Here I leave you another option in a simpler way. 
```sql
select * from creditcardmarketing
order by Q1_balance asc 
limit 10,1;
```

### 3. Cleaning, processing and modeling your data

Great work at the beginning loading your database from SQL, congrats!!

During this part you had to deal with cleaning and preprocessing techniques that you have been learning during the course many times. 

Sometimes it's a good idea try using some variables and leaving some out, specially when you have a lot of dummy variables. 

You tried different classification techniques, a lot of them, getting some results from SMOTE, DecisionTreeClassifier or KNN, great, great job here! You have to be really happy with your work here. I missed some explanation about each model that you used and a longer conclusion to understand why you prefer to use a model than another, what is the main characteristic of each model and some problems that you found using it...

Just a detail: it would be great if you start to use .py files when you store the functions that you are gonna use in your jupyter notebook. 

Overall, you did a great job and it seems clearly that you are improving a lot, congrats!! Keep working on this and your Final Project will be awesome!!
