### ISSUE TITLE
[mid-bootcamp-project] Elissa de Jong

### ISSUE THREAD

**Issue by Elissadejong** [Ironhack-Data-0621-Remote/mid-bootcamp-project#4]
https://github.com/Elissadejong/P2_creditcard_offer.git

**Comment by fromeropablo** [comment]
# Mid-Bootcamp-Project

Hello Elissa! Let's gonna check your mid-bootcamp project!!

### 1. ReadME and Repo Structure

First of all, good READMe! You have explained how your project is developing and what steps are you taking every time, that's really cool! The structured it's good but you can always your presentation with some tricks.

Just a few details:

- Great that you tried to add an image at the beginning of your presentation. Here I leave you the best way to do it:

```markdown
![Zones of the court](./images/polygon_court.png)
```
The first part of the line, the one inside square brackets, represents the words that should appear in case that the image doesn't show properly. The second part is the image itself. To do in the same way you should create a folder in your repo (from Visual Studio) called `images` and save the images you wanna show there.

- Good work showing the Python modules that you used for your project but you can do it in a prettier way:
```markdown
[Pandas](https://pandas.pydata.org/docs/)
```
Similar to what I told you before, the first part is the title or what every user will see in your repo and the second part is the link to the documentation of that module. It will appear in Github in blue words as a hyperlink.

- Great that you added a little explanation about the meaning of the columns of your dataset. It helps to orientate readers on what they are gonna see in your project. 

- In my opinion, in the workflow part it's better to summarize your steps in a few words for each one. A good exercise that I use for myself is that I want to write what I would like to read from other people. I apply this "rule" some times but it can also work with ReadMEs jajaja.

- The structure of your repo is good but you can improve and show a better repo separate in different folders. Remember that you can create folders from Visual Studio Code and it's great if you create a folder for your data, another one with your notebooks or solutions in this case and another one with your .py files. It will improve your presentation way better!

At all, good job in this part!

### 2. SQL

Okay, so now it's time to check your SQL exercise. The set of questions is very complete and it was added to reinforce your knowledge of such an important skill as it is manage structured databases. 

Great work in this part, you have answered in such a great way, congrats!

- At the beginning, it's preferred to create the database and drop any possible existing table or database. It would be like this:
```sql
drop table if exists creditcardmarketing;
create table credit_card_data  (
	Customer_Number	int,
    Offer_Accepted varchar(20),
	Reward varchar(20),  
	Mailer_Type varchar(20),
    Income_Level varchar(20),
    Bank_Accounts_Open int,
    Overdraft_Protection varchar(20) ,
    Credit_Rating varchar(20),
    Credit_Cards_Held int,
    Homes_Owned int,
    Household_Size int,
    Own_Your_Home varchar(20),
    Average_Balance float,
    Q1_Balance float,
    Q2_Balance float,
    Q3_Balance float,
    Q4_Balance float,
    primary key (Customer_Number)
    );
```

- Being picky, in this question (**Is there any correlation between the columns `credit_cards_held` and `number_of_bank_accounts_open`?**) I will add some clauses to see the result clearly:
```sql
select Credit_Cards_Held, avg(Bank_Accounts_Open) as Average_Number_Bank_Accounts, count(*) as Number_of_Customers
from credit_card_data
group by Credit_Cards_Held
order by Credit_Cards_Held;
```

- In exercise **15** your query seems good for what we asked, but it exists at least one option saving some code lines. It would be like this:
```sql
select credit_rating, round(avg(Average_balance),2)
from creditcardmarketing
where credit_rating in ('High','medium')
group by credit_rating; 
```
- Finally, in last question (**17**), you can reduce your code lines aswell. Here I leave you another option in a simpler way. 
```sql
select * from creditcardmarketing
order by Q1_balance asc 
limit 10,1;
```

### 3. Cleaning, processing and modeling your data

During this part you had to deal with cleaning and preprocessing techniques that you have been learning during the course many times. 

It would be great if in the future you are able to import your database in a jupyter notebook directly from SQL. 

Also, in your cleaning part, it's important to explain why you fill your missing values with the mean of the column. It's a good practice what you did but it gives readers some context about what you are doing in every step. 

Great work with your `regex` function, it's really useful, congrats!!

Amazing work in your preprocessing part, you've done everything in a perfect way!!!

Just a detail: it would be great if you start to use .py files when you store the functions that you are gonna use in your jupyter notebook. 

Wow, your Machine Learning part it's absolutely perfect! You tried a lot of models using different techniques after cleaning your data with detail. You have to be really happy of your work here because it's great, congrats!

I would give you a tip for your explanation marks. It's better for readers to show them in a markdown format. You can change the format of your cell to markdown using ctrl/command + M.

Really cool that you have noted the points that you have to improve in further steps, that's a key exercise for yourself to be a better data analyst/scientist!

Keep improving in the same way and your final project will be great for sure!!
