### ISSUE TITLE
project 2 jack

### ISSUE THREAD

**Issue by jack93g** [Ironhack-Data-0621-Remote/mid-bootcamp-project#6]
https://github.com/jack93g/Mid-Bootcamp-Project-Classification

**Comment by fromeropablo** [comment]
# Mid-Bootcamp-Project

Hello Jack! Let's gonna check your mid-bootcamp project!!

### 1. ReadME and Repo Structure

First of all, amazing ReadME! In my opinion it's the ReadME that you want to look at when you open a repo from someone in Github because you are interested in the topic covered. Congrats on this and keep doing similar ReadMEs in further projects!

The structure of your repo is great aswell, creating different folders for your deliverables, data and images.

### 2. SQL

Okay, so now it's time to check your SQL exercise. The set of questions is very complete and it was added to reinforce your knowledge of such an important skill as it is manage structured databases. 

Great work in this part, you have answered in such a great way, congrats!

- In exercise **15** your query seems good for what we asked, but it exists at least one option saving some code lines. It would be like this:
```sql
select credit_rating, round(avg(Average_balance),2)
from creditcardmarketing
where credit_rating in ('High','medium')
group by credit_rating; 
```
- Finally, in last question (**17**), you can reduce your code lines aswell. Here I leave you another option in a simpler way. 
```sql
select * from creditcardmarketing
order by Q1_balance asc 
limit 10,1;
```

### 3. Cleaning, processing and modeling your data

During this part you had to deal with cleaning and preprocessing techniques that you have been learning during the course many times. 

Jack, to be honest, your jupyter notebook is incredible, absolutely perfect! Well explained with markdown cells, a lot of useful plots and a good structure of your work. Literally I can't say anything to improve it. 

Well, maybe one jaja. I missed a folder containing all your functions in a .py file and calling them directly in the notebook instead of defining them inside. Anyway, you have to be extremely proud of your work here, it's a great project, congrats!


Overall, you have completed a great project with anything left outside your deliverables. In my opinion, adding a .py file for those functions you should pinned this project in your GitHub profile. Congratulations again!
