### ISSUE TITLE
Tom Dubun classification project

### ISSUE THREAD

**Issue by TomDubun** [Ironhack-Data-0621-Remote/mid-bootcamp-project#8]
https://github.com/TomDubun/mid-bootcamp-project.git
please check the "project" folder

**Comment by AnaAGG** [comment]
# mid bootcamp project

Hello hello Tom 🙋🏻‍♀️ , here we go with the revision of your project 

## README

- You specify the libreries used in this project which is perfect, if you include the link to the official documentations the readme would be perfect 😉. 

    How can we insert a link in the readme?

    ```
    [pandas](https://pandas.pydata.org/docs/)
    ```
## Repository structure

Let's go with the structure of the repo! 

- You have a folder called `checkpoints`, this is a folder that is automatically generated when we create jupyters and is like a "backup". Ideally we should put it in the `gitignore` because the "original" files are already in the repo. 


- Here are some tips to keep your repo perfectly tidy: 

    - You can create multiple folders to save the different files, for example: 

    - The data folder where we will store the csv with the data we are going to work with.

    - The notebooks folder where we store the jupyters. If we also have several jupyters and we number them to have clear the working order, it would be perfect.

    - The folder of the `images` where we will save all the images generated in the project.

    - The sql folder where we will save all sql files.

## Syntax code

- Wow Tom!! Very good job with the SQL part of the project 🔝🔥

- For the future, remember the functions should be in the `.py` file and import them in the jupyter. 
- Regarding the functions, when we write a function it mandatory to create a docstring. 

    *What is it?*

    Is a string that give us the functionality of the code. What to put in the docstring of a function?

    - What the function does
    - The parameters it receives and what type they are
    - What it returns

        ```python
        # taking one of your functions as an example:

        def alphanum(df):
            '''
            Removes special characters from column names (except "_")
            Args: 
                df(dataframe) : the dataframe on which we want to apply the cleanup
            Returns 
                The same input dataframe where 
                
                17:30
                data full time presentaciones a las 15
            '''
            alpha=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
            numeric= ['0','1','2','3','4','5','6','7','8','9']
            keep=['_']
            cols = df.columns
            new_col_names=[]
            for col in cols:
                new_col = ''
                for arg in col:
                    if (arg in numeric) or (arg in alpha) or (arg in keep):
                        new_col += arg
                new_col_names.append(new_col)
            df.columns = new_col_names
            return df
        ```
        [Here](https://www.datacamp.com/community/tutorials/docstrings-python) some documentation about docstrings in python

- As a challenge for the future, when you make the distplots of the distribution of numerical variables I propose the following: 

    Instead of plotting all the graphs one below the other, try using the `subplots` of `matplotlib`. That will allow us to create multiple subplots given specific dimensions, i.e. 3 columns and 3 rows (a total of 9 plots). 

    This will allow us to visualise our data at a glance. 

    [Here](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplots.html) is some documentation about this method

- Super that at the end you put a summary of all the models you made Tom! It helps a lot to follow your work

- If you look at the whole project you are testing the same model but with different datasets. You are repeating the same code over and over again. When this happens, it's time to... create a function! In this context one thing you can do is:
  
  - Create a function to confusion matrix
  - Create a function to initialize the modelm fit, get the score and make the predictions


- Regarding the KNN model, when you choose the best value of k you did it perfect. As a detail, in pyhton we have the `KElbowVisualizer` method which allow us to select optimal number of cluster in a simple way by fitting the model with a range of values. 

    [Here](https://www.scikit-yb.org/en/latest/api/cluster/elbow.html) some documentation. 

    ```python
    # here an example of what the code would look like

    # set the model
    model = KMeans()

    #inizialice the Visuaized. k correspond with the range of k we want to test 
    visualizer = KElbowVisualizer(model, k=(2,15), metric='silhouette')

    # fit the model for all the k created in the previous step
    visualizer.fit(X)  

    # return a plot highlighting the optimum number of k     
    visualizer.show()
    ```
- I missed a bit more commentary in the jupyter, i.e. interpretation of the results you get. What do they mean or how can we interpret the confusion matrix, what conclusions do you draw from them etc.

## TODOs

Well, here is a little recap of the comments I made to you

- Atomize code and create more functions
- Modulate the code taking the functions to the `py` file. If you have any doubt, let me know and we'll see it together.
- More documentation or explanation of results
- Docstrings in the functions
- Put the docstrings links in the readme

Overall super job Tom! Incredible evolution in your code and in the presentation of the project, congratulations 💪👏🏽! 


![image](https://user-images.githubusercontent.com/75084991/132743107-c05e21bc-9e00-4ed1-a5d5-63226c5d3ea9.png)
